# Generated by Django 5.2.17 on 2026-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallet_wallettransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('DELIVERY', 'Delivery Person')], default='BUYER', max_length=20),
        ),
    ]
