# Generated by Django 5.2.17 on 2026-09-02 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_delivery_person_order_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_PLACED', 'Order placed'), ('ORDER_ACCEPTED', 'Order accepted'), ('ORDER_PREPARING', 'Order preparing'), ('ORDER_READY', 'Ready for delivery'), ('DELIVERY_ASSIGNED', 'Delivery assigned'), ('ORDER_PICKED_UP', 'Order picked up'), ('ORDER_OUT_FOR_DELIVERY', 'Out for delivery'), ('ORDER_DELIVERED', 'Order delivered'), ('ORDER_COMPLETED', 'Order completed'), ('ORDER_CANCELLED', 'Order cancelled')], max_length=40)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
